set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData1[9]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData1[3]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData1[0]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData1[1]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData1[2]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData1[4]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData1[5]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData1[6]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData1[7]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData1[13]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData1[14]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData1[11]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData1[12]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData1[17]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData1[18]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData1[15]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData1[16]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData1[21]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData1[22]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData1[19]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData1[20]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData1[25]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData1[26]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData1[23]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData1[24]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData1[29]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData1[30]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData1[27]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData1[28]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData1[31]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData1[8]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData1[10]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData2[3]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData2[0]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData2[1]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData2[2]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData2[4]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData2[5]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData2[6]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData2[7]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData2[13]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData2[14]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData2[11]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData2[12]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData2[8]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData2[9]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData2[10]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData2[19]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData2[15]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData2[16]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData2[17]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData2[18]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData2[20]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData2[25]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData2[26]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData2[21]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData2[22]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData2[23]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData2[24]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData2[29]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData2[30]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData2[27]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData2[28]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData2[31]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData3[6]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData3[2]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData3[0]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData3[1]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData3[3]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData3[4]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData3[5]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData3[7]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData3[8]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData3[9]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData3[12]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData3[13]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData3[10]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData3[11]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData3[16]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData3[17]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData3[14]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData3[15]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData3[20]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData3[21]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData3[18]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData3[19]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData3[24]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData3[25]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData3[22]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData3[23]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData3[28]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData3[29]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData3[26]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData3[27]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData3[30]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData3[31]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData4[6]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData4[2]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData4[0]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData4[1]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData4[3]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData4[4]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData4[5]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData4[7]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData4[8]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData4[9]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData4[12]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData4[13]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData4[10]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData4[11]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData4[16]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData4[17]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData4[14]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData4[15]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData4[20]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData4[21]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData4[18]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData4[19]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData4[24]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData4[25]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData4[22]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData4[23]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData4[28]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData4[29]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData4[26]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData4[27]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData4[30]}]
set_property MARK_DEBUG true [get_nets {design_riscv_i/RegisterSet/AesWrData4[31]}]

set_property MARK_DEBUG true [get_nets design_riscv_i/GCLK_1]

set_property MARK_DEBUG true [get_nets design_riscv_i/inverse_0/val]
create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 8192 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list GCLK_IBUF]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {design_riscv_i/Split_0_Out4[0]} {design_riscv_i/Split_0_Out4[1]} {design_riscv_i/Split_0_Out4[2]} {design_riscv_i/Split_0_Out4[3]} {design_riscv_i/Split_0_Out4[4]} {design_riscv_i/Split_0_Out4[5]} {design_riscv_i/Split_0_Out4[6]} {design_riscv_i/Split_0_Out4[7]} {design_riscv_i/Split_0_Out4[8]} {design_riscv_i/Split_0_Out4[9]} {design_riscv_i/Split_0_Out4[10]} {design_riscv_i/Split_0_Out4[11]} {design_riscv_i/Split_0_Out4[12]} {design_riscv_i/Split_0_Out4[13]} {design_riscv_i/Split_0_Out4[14]} {design_riscv_i/Split_0_Out4[15]} {design_riscv_i/Split_0_Out4[16]} {design_riscv_i/Split_0_Out4[17]} {design_riscv_i/Split_0_Out4[18]} {design_riscv_i/Split_0_Out4[19]} {design_riscv_i/Split_0_Out4[20]} {design_riscv_i/Split_0_Out4[21]} {design_riscv_i/Split_0_Out4[22]} {design_riscv_i/Split_0_Out4[23]} {design_riscv_i/Split_0_Out4[24]} {design_riscv_i/Split_0_Out4[25]} {design_riscv_i/Split_0_Out4[26]} {design_riscv_i/Split_0_Out4[27]} {design_riscv_i/Split_0_Out4[28]} {design_riscv_i/Split_0_Out4[29]} {design_riscv_i/Split_0_Out4[30]} {design_riscv_i/Split_0_Out4[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {design_riscv_i/Split_0_Out3[0]} {design_riscv_i/Split_0_Out3[1]} {design_riscv_i/Split_0_Out3[2]} {design_riscv_i/Split_0_Out3[3]} {design_riscv_i/Split_0_Out3[4]} {design_riscv_i/Split_0_Out3[5]} {design_riscv_i/Split_0_Out3[6]} {design_riscv_i/Split_0_Out3[7]} {design_riscv_i/Split_0_Out3[8]} {design_riscv_i/Split_0_Out3[9]} {design_riscv_i/Split_0_Out3[10]} {design_riscv_i/Split_0_Out3[11]} {design_riscv_i/Split_0_Out3[12]} {design_riscv_i/Split_0_Out3[13]} {design_riscv_i/Split_0_Out3[14]} {design_riscv_i/Split_0_Out3[15]} {design_riscv_i/Split_0_Out3[16]} {design_riscv_i/Split_0_Out3[17]} {design_riscv_i/Split_0_Out3[18]} {design_riscv_i/Split_0_Out3[19]} {design_riscv_i/Split_0_Out3[20]} {design_riscv_i/Split_0_Out3[21]} {design_riscv_i/Split_0_Out3[22]} {design_riscv_i/Split_0_Out3[23]} {design_riscv_i/Split_0_Out3[24]} {design_riscv_i/Split_0_Out3[25]} {design_riscv_i/Split_0_Out3[26]} {design_riscv_i/Split_0_Out3[27]} {design_riscv_i/Split_0_Out3[28]} {design_riscv_i/Split_0_Out3[29]} {design_riscv_i/Split_0_Out3[30]} {design_riscv_i/Split_0_Out3[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 32 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {design_riscv_i/Split_0_Out2[0]} {design_riscv_i/Split_0_Out2[1]} {design_riscv_i/Split_0_Out2[2]} {design_riscv_i/Split_0_Out2[3]} {design_riscv_i/Split_0_Out2[4]} {design_riscv_i/Split_0_Out2[5]} {design_riscv_i/Split_0_Out2[6]} {design_riscv_i/Split_0_Out2[7]} {design_riscv_i/Split_0_Out2[8]} {design_riscv_i/Split_0_Out2[9]} {design_riscv_i/Split_0_Out2[10]} {design_riscv_i/Split_0_Out2[11]} {design_riscv_i/Split_0_Out2[12]} {design_riscv_i/Split_0_Out2[13]} {design_riscv_i/Split_0_Out2[14]} {design_riscv_i/Split_0_Out2[15]} {design_riscv_i/Split_0_Out2[16]} {design_riscv_i/Split_0_Out2[17]} {design_riscv_i/Split_0_Out2[18]} {design_riscv_i/Split_0_Out2[19]} {design_riscv_i/Split_0_Out2[20]} {design_riscv_i/Split_0_Out2[21]} {design_riscv_i/Split_0_Out2[22]} {design_riscv_i/Split_0_Out2[23]} {design_riscv_i/Split_0_Out2[24]} {design_riscv_i/Split_0_Out2[25]} {design_riscv_i/Split_0_Out2[26]} {design_riscv_i/Split_0_Out2[27]} {design_riscv_i/Split_0_Out2[28]} {design_riscv_i/Split_0_Out2[29]} {design_riscv_i/Split_0_Out2[30]} {design_riscv_i/Split_0_Out2[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {design_riscv_i/Split_0_Out1[0]} {design_riscv_i/Split_0_Out1[1]} {design_riscv_i/Split_0_Out1[2]} {design_riscv_i/Split_0_Out1[3]} {design_riscv_i/Split_0_Out1[4]} {design_riscv_i/Split_0_Out1[5]} {design_riscv_i/Split_0_Out1[6]} {design_riscv_i/Split_0_Out1[7]} {design_riscv_i/Split_0_Out1[8]} {design_riscv_i/Split_0_Out1[9]} {design_riscv_i/Split_0_Out1[10]} {design_riscv_i/Split_0_Out1[11]} {design_riscv_i/Split_0_Out1[12]} {design_riscv_i/Split_0_Out1[13]} {design_riscv_i/Split_0_Out1[14]} {design_riscv_i/Split_0_Out1[15]} {design_riscv_i/Split_0_Out1[16]} {design_riscv_i/Split_0_Out1[17]} {design_riscv_i/Split_0_Out1[18]} {design_riscv_i/Split_0_Out1[19]} {design_riscv_i/Split_0_Out1[20]} {design_riscv_i/Split_0_Out1[21]} {design_riscv_i/Split_0_Out1[22]} {design_riscv_i/Split_0_Out1[23]} {design_riscv_i/Split_0_Out1[24]} {design_riscv_i/Split_0_Out1[25]} {design_riscv_i/Split_0_Out1[26]} {design_riscv_i/Split_0_Out1[27]} {design_riscv_i/Split_0_Out1[28]} {design_riscv_i/Split_0_Out1[29]} {design_riscv_i/Split_0_Out1[30]} {design_riscv_i/Split_0_Out1[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {design_riscv_i/DecodeStage_0_InstO[0]} {design_riscv_i/DecodeStage_0_InstO[1]} {design_riscv_i/DecodeStage_0_InstO[2]} {design_riscv_i/DecodeStage_0_InstO[3]} {design_riscv_i/DecodeStage_0_InstO[4]} {design_riscv_i/DecodeStage_0_InstO[5]} {design_riscv_i/DecodeStage_0_InstO[6]} {design_riscv_i/DecodeStage_0_InstO[7]} {design_riscv_i/DecodeStage_0_InstO[8]} {design_riscv_i/DecodeStage_0_InstO[9]} {design_riscv_i/DecodeStage_0_InstO[10]} {design_riscv_i/DecodeStage_0_InstO[11]} {design_riscv_i/DecodeStage_0_InstO[12]} {design_riscv_i/DecodeStage_0_InstO[13]} {design_riscv_i/DecodeStage_0_InstO[14]} {design_riscv_i/DecodeStage_0_InstO[15]} {design_riscv_i/DecodeStage_0_InstO[16]} {design_riscv_i/DecodeStage_0_InstO[17]} {design_riscv_i/DecodeStage_0_InstO[18]} {design_riscv_i/DecodeStage_0_InstO[19]} {design_riscv_i/DecodeStage_0_InstO[20]} {design_riscv_i/DecodeStage_0_InstO[21]} {design_riscv_i/DecodeStage_0_InstO[22]} {design_riscv_i/DecodeStage_0_InstO[23]} {design_riscv_i/DecodeStage_0_InstO[24]} {design_riscv_i/DecodeStage_0_InstO[25]} {design_riscv_i/DecodeStage_0_InstO[26]} {design_riscv_i/DecodeStage_0_InstO[27]} {design_riscv_i/DecodeStage_0_InstO[28]} {design_riscv_i/DecodeStage_0_InstO[29]} {design_riscv_i/DecodeStage_0_InstO[30]} {design_riscv_i/DecodeStage_0_InstO[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 32 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {design_riscv_i/DecodeStage_0_PCO[0]} {design_riscv_i/DecodeStage_0_PCO[1]} {design_riscv_i/DecodeStage_0_PCO[2]} {design_riscv_i/DecodeStage_0_PCO[3]} {design_riscv_i/DecodeStage_0_PCO[4]} {design_riscv_i/DecodeStage_0_PCO[5]} {design_riscv_i/DecodeStage_0_PCO[6]} {design_riscv_i/DecodeStage_0_PCO[7]} {design_riscv_i/DecodeStage_0_PCO[8]} {design_riscv_i/DecodeStage_0_PCO[9]} {design_riscv_i/DecodeStage_0_PCO[10]} {design_riscv_i/DecodeStage_0_PCO[11]} {design_riscv_i/DecodeStage_0_PCO[12]} {design_riscv_i/DecodeStage_0_PCO[13]} {design_riscv_i/DecodeStage_0_PCO[14]} {design_riscv_i/DecodeStage_0_PCO[15]} {design_riscv_i/DecodeStage_0_PCO[16]} {design_riscv_i/DecodeStage_0_PCO[17]} {design_riscv_i/DecodeStage_0_PCO[18]} {design_riscv_i/DecodeStage_0_PCO[19]} {design_riscv_i/DecodeStage_0_PCO[20]} {design_riscv_i/DecodeStage_0_PCO[21]} {design_riscv_i/DecodeStage_0_PCO[22]} {design_riscv_i/DecodeStage_0_PCO[23]} {design_riscv_i/DecodeStage_0_PCO[24]} {design_riscv_i/DecodeStage_0_PCO[25]} {design_riscv_i/DecodeStage_0_PCO[26]} {design_riscv_i/DecodeStage_0_PCO[27]} {design_riscv_i/DecodeStage_0_PCO[28]} {design_riscv_i/DecodeStage_0_PCO[29]} {design_riscv_i/DecodeStage_0_PCO[30]} {design_riscv_i/DecodeStage_0_PCO[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 32 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {design_riscv_i/RegisterSet/AesWrData1[0]} {design_riscv_i/RegisterSet/AesWrData1[1]} {design_riscv_i/RegisterSet/AesWrData1[2]} {design_riscv_i/RegisterSet/AesWrData1[3]} {design_riscv_i/RegisterSet/AesWrData1[4]} {design_riscv_i/RegisterSet/AesWrData1[5]} {design_riscv_i/RegisterSet/AesWrData1[6]} {design_riscv_i/RegisterSet/AesWrData1[7]} {design_riscv_i/RegisterSet/AesWrData1[8]} {design_riscv_i/RegisterSet/AesWrData1[9]} {design_riscv_i/RegisterSet/AesWrData1[10]} {design_riscv_i/RegisterSet/AesWrData1[11]} {design_riscv_i/RegisterSet/AesWrData1[12]} {design_riscv_i/RegisterSet/AesWrData1[13]} {design_riscv_i/RegisterSet/AesWrData1[14]} {design_riscv_i/RegisterSet/AesWrData1[15]} {design_riscv_i/RegisterSet/AesWrData1[16]} {design_riscv_i/RegisterSet/AesWrData1[17]} {design_riscv_i/RegisterSet/AesWrData1[18]} {design_riscv_i/RegisterSet/AesWrData1[19]} {design_riscv_i/RegisterSet/AesWrData1[20]} {design_riscv_i/RegisterSet/AesWrData1[21]} {design_riscv_i/RegisterSet/AesWrData1[22]} {design_riscv_i/RegisterSet/AesWrData1[23]} {design_riscv_i/RegisterSet/AesWrData1[24]} {design_riscv_i/RegisterSet/AesWrData1[25]} {design_riscv_i/RegisterSet/AesWrData1[26]} {design_riscv_i/RegisterSet/AesWrData1[27]} {design_riscv_i/RegisterSet/AesWrData1[28]} {design_riscv_i/RegisterSet/AesWrData1[29]} {design_riscv_i/RegisterSet/AesWrData1[30]} {design_riscv_i/RegisterSet/AesWrData1[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 32 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {design_riscv_i/RegisterSet/AesWrData3[0]} {design_riscv_i/RegisterSet/AesWrData3[1]} {design_riscv_i/RegisterSet/AesWrData3[2]} {design_riscv_i/RegisterSet/AesWrData3[3]} {design_riscv_i/RegisterSet/AesWrData3[4]} {design_riscv_i/RegisterSet/AesWrData3[5]} {design_riscv_i/RegisterSet/AesWrData3[6]} {design_riscv_i/RegisterSet/AesWrData3[7]} {design_riscv_i/RegisterSet/AesWrData3[8]} {design_riscv_i/RegisterSet/AesWrData3[9]} {design_riscv_i/RegisterSet/AesWrData3[10]} {design_riscv_i/RegisterSet/AesWrData3[11]} {design_riscv_i/RegisterSet/AesWrData3[12]} {design_riscv_i/RegisterSet/AesWrData3[13]} {design_riscv_i/RegisterSet/AesWrData3[14]} {design_riscv_i/RegisterSet/AesWrData3[15]} {design_riscv_i/RegisterSet/AesWrData3[16]} {design_riscv_i/RegisterSet/AesWrData3[17]} {design_riscv_i/RegisterSet/AesWrData3[18]} {design_riscv_i/RegisterSet/AesWrData3[19]} {design_riscv_i/RegisterSet/AesWrData3[20]} {design_riscv_i/RegisterSet/AesWrData3[21]} {design_riscv_i/RegisterSet/AesWrData3[22]} {design_riscv_i/RegisterSet/AesWrData3[23]} {design_riscv_i/RegisterSet/AesWrData3[24]} {design_riscv_i/RegisterSet/AesWrData3[25]} {design_riscv_i/RegisterSet/AesWrData3[26]} {design_riscv_i/RegisterSet/AesWrData3[27]} {design_riscv_i/RegisterSet/AesWrData3[28]} {design_riscv_i/RegisterSet/AesWrData3[29]} {design_riscv_i/RegisterSet/AesWrData3[30]} {design_riscv_i/RegisterSet/AesWrData3[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 32 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {design_riscv_i/RegisterSet/AesWrData4[0]} {design_riscv_i/RegisterSet/AesWrData4[1]} {design_riscv_i/RegisterSet/AesWrData4[2]} {design_riscv_i/RegisterSet/AesWrData4[3]} {design_riscv_i/RegisterSet/AesWrData4[4]} {design_riscv_i/RegisterSet/AesWrData4[5]} {design_riscv_i/RegisterSet/AesWrData4[6]} {design_riscv_i/RegisterSet/AesWrData4[7]} {design_riscv_i/RegisterSet/AesWrData4[8]} {design_riscv_i/RegisterSet/AesWrData4[9]} {design_riscv_i/RegisterSet/AesWrData4[10]} {design_riscv_i/RegisterSet/AesWrData4[11]} {design_riscv_i/RegisterSet/AesWrData4[12]} {design_riscv_i/RegisterSet/AesWrData4[13]} {design_riscv_i/RegisterSet/AesWrData4[14]} {design_riscv_i/RegisterSet/AesWrData4[15]} {design_riscv_i/RegisterSet/AesWrData4[16]} {design_riscv_i/RegisterSet/AesWrData4[17]} {design_riscv_i/RegisterSet/AesWrData4[18]} {design_riscv_i/RegisterSet/AesWrData4[19]} {design_riscv_i/RegisterSet/AesWrData4[20]} {design_riscv_i/RegisterSet/AesWrData4[21]} {design_riscv_i/RegisterSet/AesWrData4[22]} {design_riscv_i/RegisterSet/AesWrData4[23]} {design_riscv_i/RegisterSet/AesWrData4[24]} {design_riscv_i/RegisterSet/AesWrData4[25]} {design_riscv_i/RegisterSet/AesWrData4[26]} {design_riscv_i/RegisterSet/AesWrData4[27]} {design_riscv_i/RegisterSet/AesWrData4[28]} {design_riscv_i/RegisterSet/AesWrData4[29]} {design_riscv_i/RegisterSet/AesWrData4[30]} {design_riscv_i/RegisterSet/AesWrData4[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 32 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {design_riscv_i/RegisterSet/AesWrData2[0]} {design_riscv_i/RegisterSet/AesWrData2[1]} {design_riscv_i/RegisterSet/AesWrData2[2]} {design_riscv_i/RegisterSet/AesWrData2[3]} {design_riscv_i/RegisterSet/AesWrData2[4]} {design_riscv_i/RegisterSet/AesWrData2[5]} {design_riscv_i/RegisterSet/AesWrData2[6]} {design_riscv_i/RegisterSet/AesWrData2[7]} {design_riscv_i/RegisterSet/AesWrData2[8]} {design_riscv_i/RegisterSet/AesWrData2[9]} {design_riscv_i/RegisterSet/AesWrData2[10]} {design_riscv_i/RegisterSet/AesWrData2[11]} {design_riscv_i/RegisterSet/AesWrData2[12]} {design_riscv_i/RegisterSet/AesWrData2[13]} {design_riscv_i/RegisterSet/AesWrData2[14]} {design_riscv_i/RegisterSet/AesWrData2[15]} {design_riscv_i/RegisterSet/AesWrData2[16]} {design_riscv_i/RegisterSet/AesWrData2[17]} {design_riscv_i/RegisterSet/AesWrData2[18]} {design_riscv_i/RegisterSet/AesWrData2[19]} {design_riscv_i/RegisterSet/AesWrData2[20]} {design_riscv_i/RegisterSet/AesWrData2[21]} {design_riscv_i/RegisterSet/AesWrData2[22]} {design_riscv_i/RegisterSet/AesWrData2[23]} {design_riscv_i/RegisterSet/AesWrData2[24]} {design_riscv_i/RegisterSet/AesWrData2[25]} {design_riscv_i/RegisterSet/AesWrData2[26]} {design_riscv_i/RegisterSet/AesWrData2[27]} {design_riscv_i/RegisterSet/AesWrData2[28]} {design_riscv_i/RegisterSet/AesWrData2[29]} {design_riscv_i/RegisterSet/AesWrData2[30]} {design_riscv_i/RegisterSet/AesWrData2[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 1 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list design_riscv_i/BTNL_1]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list design_riscv_i/BTNL_2]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list design_riscv_i/DecodeStage_0_ClearO]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list design_riscv_i/DecodeStage_InterlockO]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list design_riscv_i/GCLK_1]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list design_riscv_i/inverse_0/val]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets GCLK_IBUF]
