# File names are either absolute or relative to the parent folder of the
# vhdl_ls.toml file and supports glob-style patterns.
[libraries]
lib2.files = [
  'modules/**/*.vhd',
]
lib1.files = [
  'testbench/**/*.vhd'
]